### ISSUE TITLE
Incorrect Time Zone for Chicago

### ISSUE THREAD

**Issue by LordNacho** [drtimcooper/LatLongToTimezone#2]
Hi,

I ran the code with this coordinate:

latitude: 41.8788764, longitude: -87.6359149 (Willis Tower)

And it gave me America/Detroit, which is wrong. I tried a few other Chicago landmarks and they're wrong as well.

**Comment by ttddlplp** [comment]
Hi, I tried it on my machine, and it does return 'America/Chicago'

**Comment by LordNacho** [comment]
Is there anything locale specific in the code? It's quite strange that we get different results.

**Comment by ttddlplp** [comment]
BTW, I am using the Java library.

**Comment by LordNacho** [comment]
I was using Swift

**Comment by 2ndCharter** [comment]
Are you still seeing this issue? I ported Dr. Cooper's Java version to C# for Xamarin, which runs on iOS like the Swift version. I'm getting America/Chicago for those coordinates as well.

**Comment by joshorr** [comment]
I am seeing the issue too with the swift version.

**Comment by bjhomer** [comment]
I just re-ran the Java & Swift generators, based on the `timezones.json` file in this repository. After regenerating the Java source, it too now fails on Chicago coordinates.

**Comment by LordNacho** [comment]
Did the descriptor file change at some point? It sounds like it used to be right.

**Comment by drtimcooper** [comment]
I believe I fixed the bug.  The generator was being non-deterministic when generating code, due to my use of Set<>.  That's fixed, and also Chicago is now showing as America/Chicago.  I didn't find any root cause of the bug, but I've tried endlessly to randomise the generation process and I can't get Chicago to be in Detroit anymore, since I removed the Set<>'s.  I am having trouble releasing the CSharp version though...not being familiar with git...I've got the latest csharp version in a folder called "Tester/src"....maybe someone can help me.
